export const projects  = [
  {
    category: 'React',
    title: 'Portfolio Website',
    description: "Using React, Next.js, and styled-components I created this portfolio website with moder UI/Ux design and minimalistic approach.",
      image: '/images/portfolio-website.png',
      tags: ['React', 'Next','styled-components'],
    code: 'https://github.com/Alaa-Elghamry/portfolio_website',
    visit: 'https://alaa-elghamry-portfolio.netlify.app/',
    id: 0,
  },
  {
    category: 'Vanilla JS',
    title: 'Graduation Project',
    description: "I Designed and Developed this website for our Graduation Project AlexCore (a 32 RISC-v microprocessor) the website is fully responsive with an interactive user interface, video backgroung, dark mood, and cool Animations.",
      image: '/images/Graduation-Project.png',
      tags: ['JavaScript', 'HTML5', 'CSS3', 'Responsive'],
    code: 'https://github.com/Alaa-Elghamry/Graduation-Project',
    visit: 'https://alaa-elghamry.github.io/Graduation-Project/',
    id: 1,
  },
  {
    category: 'Vanilla JS',
    title: 'Bankist',
    description:"This is a landing page for online banking made use HTML, CSS and Vanilla javascript advanced DOM manipulation. some features like:- Lazy Loading Images, Dynamic Cards, and Testimonial Slider.",
    image: '/images/Bankist.png',
    tags: ['JavaScript', 'HTML5', 'CSS3', 'Responsive'],
    code: 'https://github.com/Alaa-Elghamry/Bankist-Website',
    visit: 'https://alaa-elghamry.github.io/Bankist-Website/',
    id: 2,
  },
  {
    category: 'Animation',
    title: 'Magic Menu',
    description: "A 3D Menu with cool Animation built with HTML & CSS only!",
      image: '/images/magic-menu.png',
      tags: ['HTML5', 'CSS3'],
    code: 'https://github.com/Alaa-Elghamry/Magic-Menu',
    visit: 'https://github.com/Alaa-Elghamry/Magic-Menu',
    id: 3,
  },
  {
    category: 'Sass',
    title: 'Natours',
    description: "A Fancy looking website with advanced css features for a tourism company that organizes tours in nature.",
      image: '/images/Natours.png',
      tags: ['Sass', 'HTML5', 'Responsive', 'Animation'],
    code: 'https://github.com/Alaa-Elghamry/Natours-Project',
    visit: 'https://alaa-elghamry.github.io/Natours-Project/',
    id: 4,
  },
  {
    category: 'Sass',
    title: 'Nexter',
    description: "Nexter is a website to apply different CSS Grid technics.",
    image: '/images/Nexter.png',
    tags: ['Sass', 'HTML5', 'Responsive'],
    code: 'https://github.com/Alaa-Elghamry/NEXTER',
    visit: 'https://alaa-elghamry.github.io/NEXTER/',
    id: 5,
  },
  
  {
    category: 'Bootstrap',
    title: 'Candy Museum',
    description: "A simple bootstrap website that doesn't look so bootstrapy.",
      image: '/images/Candy-Museum.png',
      tags: ['HTML5', 'CSS3','Bootstrap'],
    code: 'https://github.com/Alaa-Elghamry/Candy-Museum',
    visit: 'https://alaa-elghamry.github.io/Candy-Museum/',
    id: 6,
  },
  {
    category: 'React',
    title: 'Face Detector',
    description: "Using This React Application you can detect faces in pictures and tag friends. ",
      image: '/images/face-detector.png',
      tags: ['React','face-API'],
    code: 'https://github.com/Alaa-Elghamry/React-Face-Detection',
    visit: 'https://github.com/Alaa-Elghamry/React-Face-Detection',
    id: 7,
  },
];

export const TimeLineData = [
  { year: 2017, text: 'Started my journey', },
  { year: 2018, text: 'Learned Basic Programming and Electronics', },
  { year: 2019, text: 'Studied Digital Design', },
  { year: 2020, text: 'Discovered a Passion For Front-End Development', },
  { year: 2021, text: 'Learning More Everyday..', },
];